apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: worker
          image: 760773573647.dkr.ecr.us-east-1.amazonaws.com/dev-worker:IMAGE_TAG
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/760773573647/dev-job-queue"